import seed_db
conn = seed_db.mysql.connector.connect(**seed_db.DB)
cur = conn.cursor()
cur.execute('SELECT id, employee_code, first_name, last_name FROM employees_core')
print('Employees:', cur.fetchall())
cur.execute('SELECT COUNT(*) FROM attendance')
print('Attendance:', cur.fetchone())
cur.execute('SELECT COUNT(*) FROM leave_balances')
print('Leave balances:', cur.fetchone())
cur.execute('SELECT COUNT(*) FROM compensation')
print('Compensation:', cur.fetchone())
cur.execute('SELECT COUNT(*) FROM appraisals')
print('Appraisals:', cur.fetchone())
conn.close()